steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'homepage'
      - '--image=gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA'
      - '--region=australia-southeast2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 